export const UI = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
};

export const Mission = {
  FETCH_MISSIONS_LIST_DATA: 'FETCH_MISSIONS_LIST',
  RECEIVE_MISSIONS_LIST_DATA: 'RECEIVE_MISSIONS_LIST_DATA',
  CHANGE_MISSIONS_LIST_DATA: 'CHANGE_MISSIONS_LIST_DATA',
  CHANGE_MISSIONS_LIST_STATUS: 'CHANGE_MISSIONS_LIST_STATUS',
  FETCH_ACTIVE_MISSION_DATA: 'FETCH_ACTIVE_MISSION_DATA',
  RECEIVE_ACTIVE_MISSION_DATA: 'RECEIVE_ACTIVE_MISSION_DATA',
  CHANGE_ACTIVE_MISSION_DATA: 'CHANGE_ACTIVE_MISSION_DATA',
  CHANGE_ACTIVE_MISSION_STATUS: 'CHANGE_ACTIVE_MISSION_STATUS',
  DELETE_MISSION: 'DELETE_MISSION',
  OPEN_IN_APP: 'OPEN_IN_APP',
};
