export const UI = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
};

export const Mission = {
  LOAD_MISSIONS_LIST: 'LOAD_MISSIONS_LIST',
  UPDATE_MISSIONS_LIST: 'UPDATE_MISSIONS_LIST',
  LOAD_ACTIVE_MISSION: 'LOAD_ACTIVE_MISSION',
  UPDATE_ACTIVE_MISSION: 'UPDATE_ACTIVE_MISSION',
};
