export const UI = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR'
};

export const Mission = {
  CHANGE_MISSIONS_LIST_STATUS: 'CHANGE_MISSIONS_LIST_STATUS',
  UPDATE_MISSIONS_LIST: 'UPDATE_MISSIONS_LIST',
  UPDATE_ACTIVE_MISSION: 'UPDATE_ACTIVE_MISSION'
};